# Generated by Django 4.1.3 on 2022-11-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gymdatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=55)),
                ('course', models.CharField(max_length=55)),
                ('room', models.CharField(max_length=55)),
                ('price', models.CharField(max_length=55, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
